apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: nginx-rtmp
        image: alfg/nginx-rtmp
        imagePullPolicy: IfNotPresent
        command:
          - nginx
          - "-g"
          - "daemon off;"
          - "-c"
          - "/opt/nginx/nginx.conf"
        ports:
        - containerPort: 1935
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /opt/nginx/nginx.conf
          subPath: nginx.conf
        - name: hls-storage
          mountPath: /tmp/hls
      volumes:
      - name: nginx-config
        configMap:
          name: streaming-nginx-config
      - name: hls-storage
        emptyDir: {}
